name: CI

on:
  push:
    branches: ["main"]
    paths:
      - "**.py"
      - "**.gpx"
      - "**.sh"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.py"
      - "**.gpx"
      - "**.sh"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      # - name: Store the distribution packages
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: python-package-distributions
      #     path: dist/

  test-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        pyv: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyv }}

      - name: Test cli
        shell: bash
        run: |
          chmod +x ./test/cli.test.sh
          ./test/cli.test.sh
