name: CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

env:
  artifact_name: "python-package-distributions"
  artifact_path: "dist/"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: "TRUE"
          fetch-depth: "9"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_path }}
          retention-days: 1
          compression-level: 1

  test-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        pyv: ["3.11"]
    env:
      python_version: ${{ matrix.pyv }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyv }}

      - name: Test cli
        shell: bash
        run: |
          chmod +x ./test/cli.test.sh
          ./test/cli.test.sh

  publish-to-testpypi:
    name: Publish 🐍 TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: test.pypi.org
      url: https://test.pypi.org/p/ezon-gpx

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_path }}
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
