name: test

on:
  push:
    branches: ["main"]
    paths:
      - "*.py"
      - "*.gpx"
      - "*.sh"
      - ".github/workflows/test.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "*.py"
      - "*.gpx"
      - "*.sh"
      - ".github/workflows/test.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        pyv: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyv }}
      - name: Test src/main.py
        run: |
          python src/main.py
      - name: Test cli.py
        shell: bash
        run: |
          chmod +x ./test/cli.test.sh
          ./test/cli.test.sh
